### ISSUE TITLE
feature request: suspended mode

### ISSUE THREAD

**Issue by gilbh** [victorbenichoux/ticktock#5]
Hi,

I could not find in documentation: is there a way of temporarily shutting off all ticktock calls? This is helpful for switching between debug and production modes.

Thanks!

**Comment by victorbenichoux** [comment]
Hi @gilbh !

Currently, there is no such mode, but it seems like it would be relatively easy to implement 😄 . I will try to think of a good way to do it.

**Comment by gilbh** [comment]
Great! Keep me posted when it is added.

**Comment by victorbenichoux** [comment]
What would you think of something like this:
```python
import ticktock

@ticktock.ticktock()
def f():
    ass

# these are counted
 f()
 f()
 
 ticktock.disable()
# this call is discarded
 f()
 
 ticktock.enable()
# these are counted again
 f()
 f()
 ```

**Comment by gilbh** [comment]
Fantastic.

Few small ideas:
1) instead of two separate call, make one function `toggle()`. It could take an optional `action` parameter, with: `auto`, `on`, `off', the default is `auto` which toggles the current state.
2) From the user end, my own tendency (and it is just a tendency) is to limit namespace of imports:
```
from ticktock import ticktock as tc, toggle as tc_tgl
```
I mention that b/c `@ticktock.ticktock()` is very long, compared with `@tc_tgl` 


These are just passing ideas. Keep on rocking.

**Comment by victorbenichoux** [comment]
Thanks (again) for the constructive feedback!

1. I am sort of worried about the `toggle` idea here, I am worried that it would be hard to keep track of the current enabled/disabled state of the clock (and worse, their clockcollection). In addition, it could create headaches toggling the state of a collection that has both enabled and disabled clocks (see the documentation in my PR)

2. I agree with your note on the namespace. I was being overly verbose in the example 😄 . In general, I think I would advise for importing `tick` and `ticktock` directly with `from ticktock import tick, ticktock`.

**Comment by gilbh** [comment]
Cool. As for item #2: would the user need to import disable() and enable() as well? Or any way to reduce that? (Sorry for being a stickler, all's is well with things as they are!).

**Comment by victorbenichoux** [comment]
At the moment, yes. I'll see about adding the `toggle` in another PR. Hopefully I'll be able to get it done tomorrow and push a new release to PyPi. I will leave this issue open as a reminder 😄 .

**Comment by victorbenichoux** [comment]
I have made a release with `enable/disable`, I will open a new issue for the implementation of the toggle! 

Thanks for contributing!
